platform :ios, '10.0'
use_frameworks!

target 'Gryphon_Example' do
  pod 'Gryphon', :path => '../'
  pod 'Alamofire', '~> 4.0'
  target 'Gryphon_Tests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
