use_frameworks!

target 'Gryphon_Example' do
  pod 'Gryphon', :path => '../'
  pod 'Alamofire', '~> 3.0'

  target 'Gryphon_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  end
end
